image: node:latest

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - npm install
    - npm run test

deploy:
  stage: deploy
  dependencies:
    - test
  script:
   - npm install
   - npm run build
   - echo "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}">.npmrc
   - npm publish
