image: node:latest

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

stages:
  - test
  - deploy

before_script:
  - cp /mnt/certs/ca.crt /digify-ca.crt

test:
  stage: test
  script:
    - npm install
    - npm run test

deploy:
  stage: deploy
  dependencies:
    - test
  script:
    - npm config set cafile /digify-ca.crt
    - npm config get cafile
    - npm install
    - npm run build
    - echo "@opensource:registry=${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/npm/" >> .npmrc
    - echo "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}" >> .npmrc
    - npm publish
