image: node:latest

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - npm install
    - npm run test

deploy:
  stage: deploy
  dependencies:
    - test
  script:
   - echo CI_API_V4_URL=${CI_API_V4_URL}
   - echo CI_PROJECT_ID=${CI_PROJECT_ID}
   - echo CI_SERVER_HOST=${CI_SERVER_HOST}
   - npm install
   - npm run build
   #  echo "@opensource:registry=${CI_API_V4_URL}" >> .npmrc
   # - npm publish
